<?php

/**
 * @file
 * The module file for Google+ feed
 */
/**
 * Hook that calls feed module to process the feed
 * 
 *@param string $user Contains uid, userid, password, feed 
 *entered on user's settings page
 */
function activitystream_googleplus_streamapi($user) {
  // User doesn't have a correct google plus ID entered.
  if (!$user->feed) {
    return;
  }

  // Use activitystream_feed module to pull information.
  $items = activitystream_feed_streamapi($user);
  return $items;
 }
/**
 *Hook for user settings form.  Will be added by activitystream module.
 * 
 *@param array $edit Values of the form fields
 */
function activitystream_googleplus_activitystream_settings(&$edit) {
  $form['activitystream_googleplus'] = array(
    '#type' => 'fieldset',
    '#title' => t('Google+ settings'),
  );
  $form['activitystream_googleplus']['activitystream_googleplus_feed'] = array(
    '#type' => 'textfield',
    '#title' => t('Feed URL'),
    '#default_value' => empty($edit['activitystream_googleplus_feed']) ? '' : $edit['activitystream_googleplus_feed'],
    '#description' => t('To get your Google+ RSS feed click and follow the directions ') . '<a href="http://googleplusrss.nodester.com/">here</a>',
  );
  return $form;
 }
//Gets Google+ icon.
function theme_activitystream_googleplus_icon() {
  return theme_image(drupal_get_path('module', 'activitystream_googleplus') . '/googlePlus.jpg', 'googleplus');
}
//Creates link to current users activity stream. 
function theme_activitystream_googleplus_item($activity) {
  $node = node_load($activity->nid);
  $date = theme('activitystream_date', $node->created);
  $user = activitystream_user_load($node->uid);
  $name = theme('activitystream_username', $user);
  return '<span class="activitystream-item">' . theme('activitystream_googleplus_icon')   . " <span>$name " . l(t($node->title, $activity->link)) . " <span class=\"activitystream-created\">$date</span></span>". l('#', 'node/' . $node->nid, array('class' => 'permalink')) . '</span>';
}
//Theme function.
function activitystream_googleplus_theme() {
  return array(
    'activitystream_googleplus_icon' => array(
      'arguments' => array(),
    ),
    'activitystream_googleplus_item' => array(
      'arguments' => array('activity' => NULL),
    ),
  );
}
